"use client";
import { useState } from "react";
import { Plus, Pencil, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { Brand } from "@/modules/brand/types";
import { useListBrandsQuery, useCreateBrandMutation, useUpdateBrandMutation, useUpdateBrandStatusMutation, useDeleteBrandMutation, useUploadBrandLogoMutation } from "@/modules/brand/brandApi";
import { CatalogHeader, RecordDialog, DeleteDialog, StatusBadge, LoadingPanel, ErrorPanel, EmptyPanel, ActionNotice, useCatalogAction, CatalogMedia, selectStyle } from "./CatalogShared";

export function BrandsPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [filter, setFilter] = useState<"" | "ACTIVE" | "INACTIVE">("");
  const query = useListBrandsQuery({ page, limit: 12, search: search || undefined, status: filter || undefined });
  const [dialog, setDialog] = useState<{ brand?: Brand }>(); const [deleting, setDeleting] = useState<Brand>();
  const [create] = useCreateBrandMutation(); const [update] = useUpdateBrandMutation(); const [status] = useUpdateBrandStatusMutation(); const [remove] = useDeleteBrandMutation(); const [upload] = useUploadBrandLogoMutation(); const action = useCatalogAction();
  return <div className="space-y-6"><CatalogHeader active="brands" title="Brands" description="Manage the brands admins can select when creating products. Save a brand, then add its logo." action={<Button onClick={() => setDialog({})}><Plus/>New brand</Button>}/><div className="flex flex-wrap items-center gap-3"><Input aria-label="Search brands" className="max-w-md" value={search} placeholder="Search brands…" onChange={e => { setSearch(e.target.value); setPage(1); }}/><select aria-label="Brand status" className={`${selectStyle} max-w-40`} value={filter} onChange={e => { setFilter(e.target.value as typeof filter); setPage(1); }}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><span className="text-xs text-muted-foreground">{query.data?.meta.total ?? 0} brands</span></div><ActionNotice action={action}/>
    {query.isLoading ? <LoadingPanel/> : query.isError ? <ErrorPanel error={query.error} retry={query.refetch}/> : !query.data?.data.length ? <EmptyPanel title="No brands found" description="Create a brand or change your search and status filters."/> : <div aria-busy={query.isFetching} className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data.data.map(brand => <article key={brand.id} className="space-y-4 rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{brand.name}</h2><p className="mt-1 text-xs text-muted-foreground">Display order {brand.sortOrder}</p></div><StatusBadge active={brand.isActive}/></div>{brand.description && <p className="text-sm text-muted-foreground">{brand.description}</p>}<CatalogMedia name={brand.name} url={brand.logo} onUpload={file => upload({ id: brand.id, file }).unwrap()}/><div className="flex flex-wrap gap-2 border-t pt-4"><Button size="sm" variant="outline" onClick={() => setDialog({ brand })}><Pencil/>Edit</Button><Button size="sm" variant="ghost" disabled={action.busy} onClick={() => void action.run(() => status({ id: brand.id, isActive: !brand.isActive }).unwrap(), "Brand status saved.")}>{brand.isActive ? "Deactivate" : "Activate"}</Button><Button size="icon-sm" variant="ghost" aria-label={`Delete ${brand.name}`} onClick={() => setDeleting(brand)}><Trash2/></Button></div></article>)}</div>}
    <div className="flex items-center justify-between border-t pt-4"><p className="text-sm text-muted-foreground">Page {page} of {Math.max(1, query.data?.meta.totalPages ?? 1)}</p><div className="flex gap-2"><Button variant="outline" disabled={page === 1 || query.isFetching} onClick={() => setPage(page - 1)}>Previous</Button><Button variant="outline" disabled={page >= (query.data?.meta.totalPages ?? 1) || query.isFetching} onClick={() => setPage(page + 1)}>Next</Button></div></div>
    {dialog && <RecordDialog title={dialog.brand ? "Edit brand" : "New brand"} description="Use the brand's recognizable name. You can upload a logo after saving." creating={!dialog.brand} initial={dialog.brand ? { ...dialog.brand, description: dialog.brand.description ?? "" } : undefined} onClose={() => setDialog(undefined)} onSave={async ({ name, description, sortOrder }) => { const body = { name, description, sortOrder }; if (dialog.brand) await update({ id: dialog.brand.id, body }).unwrap(); else { await create(body).unwrap(); setPage(1); setSearch(""); setFilter(""); } }}/ >}
    {deleting && <DeleteDialog name={deleting.name} explanation="A brand referenced by products cannot be deleted. Deactivate it to hide it from new product selections." onClose={() => setDeleting(undefined)} onDelete={async () => { await remove(deleting.id).unwrap(); if (query.data?.data.length === 1 && page > 1) setPage(page - 1); }}/ >}
  </div>;
}
