"use client";
import { useState } from "react";
import { FolderTree, Plus, Pencil, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { Category } from "@/modules/category/types";
import { useGetCategoryTreeQuery, useCreateCategoryMutation, useUpdateCategoryMutation, useUpdateCategoryStatusMutation, useDeleteCategoryMutation, useUploadCategoryImageMutation } from "@/modules/category/categoryApi";
import { flattenCategories, eligibleParents } from "../catalog.utils";
import { CatalogHeader, RecordDialog, DeleteDialog, StatusBadge, LoadingPanel, ErrorPanel, EmptyPanel, ActionNotice, useCatalogAction, CatalogMedia, SetupHint } from "./CatalogShared";
import { CategoryAssignments } from "./CategoryAssignments";

export function CategoriesPage({ initialId }: { initialId?: number }) {
  const query = useGetCategoryTreeQuery(); const rows = flattenCategories(query.data?.data ?? []);
  const [selectedId, setSelectedId] = useState(initialId); const [search, setSearch] = useState(""); const [dirty, setDirty] = useState(false);
  const [dialog, setDialog] = useState<{ category?: Category; parentId?: number }>(); const [deleting, setDeleting] = useState<Category>();
  const [create] = useCreateCategoryMutation(); const [update] = useUpdateCategoryMutation(); const [status] = useUpdateCategoryStatusMutation(); const [remove] = useDeleteCategoryMutation(); const [upload] = useUploadCategoryImageMutation(); const action = useCatalogAction();
  const selected = rows.find(row => row.id === selectedId) ?? rows[0];
  function leave() { if (dirty && !window.confirm("Discard unsaved attribute assignments?")) return false; setDirty(false); return true; }
  const filtered = rows.filter(row => row.path.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6"><CatalogHeader active="categories" title="Categories" description="Organize the catalog, then choose the variant options available in each product category." action={<Button onClick={() => setDialog({})}><Plus/>New category</Button>}/>
    <SetupHint>Use parent categories for navigation, such as <strong>Clothing → Men</strong>. Add products to a leaf category, such as <strong>T-shirts</strong>, and assign Size or Color below. A top-level category without children is also a leaf.</SetupHint><ActionNotice action={action}/>
    {query.isLoading ? <LoadingPanel/> : query.isError ? <ErrorPanel error={query.error} retry={query.refetch}/> : !rows.length ? <EmptyPanel title="Create your first category" description="Start with a category, then add subcategories where you need a more specific product grouping." action={<Button onClick={() => setDialog({})}><Plus/>New category</Button>}/> : <div className="grid items-start gap-5 lg:grid-cols-[320px_1fr]">
      <aside className="overflow-hidden rounded-2xl border bg-card"><div className="border-b p-4"><Input aria-label="Search categories" placeholder="Search category paths…" value={search} onChange={e => setSearch(e.target.value)}/><p className="mt-3 text-xs text-muted-foreground">{rows.length} categories · {rows.filter(row => row.isLeaf).length} product categories</p></div><div className="max-h-[70vh] overflow-y-auto p-2">{filtered.map(row => <button key={row.id} aria-pressed={selected?.id === row.id} onClick={() => { if (selected?.id !== row.id && leave()) setSelectedId(row.id); }} className={`flex w-full items-start gap-2 rounded-xl p-3 text-left ${selected?.id === row.id ? "bg-primary/10 ring-1 ring-primary/20" : "hover:bg-muted"}`}><FolderTree className="mt-0.5 size-4 shrink-0 text-muted-foreground"/><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{row.name}</span><span className="mt-1 block break-words text-xs text-muted-foreground">{row.path}</span><span className="mt-2 flex items-center gap-2"><span className="text-[11px] text-muted-foreground">{row.isLeaf ? "Leaf · products" : "Group"}</span><StatusBadge active={row.isActive}/></span></span></button>)}{!filtered.length && <p className="p-5 text-sm text-muted-foreground">No matching categories.</p>}</div></aside>
      {selected && <section className="min-w-0 overflow-hidden rounded-2xl border bg-card"><div className="space-y-4 border-b p-5"><div><p className="mb-1 text-xs text-muted-foreground">{selected.path}</p><h2 className="text-xl font-semibold">{selected.name}</h2>{selected.description && <p className="mt-2 text-sm text-muted-foreground">{selected.description}</p>}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setDialog({ category: selected })}><Pencil/>Edit details</Button><Button size="sm" variant="outline" onClick={() => setDialog({ parentId: selected.id })}><Plus/>Subcategory</Button><Button size="sm" variant="outline" disabled={action.busy} onClick={() => void action.run(() => status({ id: selected.id, isActive: !selected.isActive }).unwrap(), "Category status saved.")}>{selected.isActive ? "Deactivate" : "Activate"}</Button><Button size="icon-sm" variant="ghost" aria-label={`Delete ${selected.name}`} onClick={() => { if (!dirty || window.confirm("This category has unsaved assignments. Continue to delete?")) setDeleting(selected); }}><Trash2/></Button></div><CatalogMedia key={selected.id} name={selected.name} url={selected.image} onUpload={file => upload({ id: selected.id, file }).unwrap()}/></div>
        <div className="space-y-5 p-5">{!selected.isLeaf && <div className="rounded-xl bg-muted/40 p-4"><h3 className="text-sm font-semibold">Choose a child category to configure product options</h3><div className="mt-3 flex flex-wrap gap-2">{rows.filter(row => row.parentId === selected.id).map(child => <Button key={child.id} variant="outline" size="sm" onClick={() => { if (leave()) setSelectedId(child.id); }}>{child.name} →</Button>)}</div></div>}<CategoryAssignments key={selected.id} id={selected.id} enabled={selected.isLeaf && selected.isActive} onDirty={setDirty}/></div></section>}
    </div>}
    {dialog && <RecordDialog title={dialog.category ? "Edit category" : "New category"} description="Choose a parent to build your catalog hierarchy. Categories with primary products or assigned attributes cannot gain children until those references are moved or cleared." creating={!dialog.category} initial={dialog.category ? { ...dialog.category, description: dialog.category.description ?? "" } : { parentId: dialog.parentId ?? null }} parents={eligibleParents(rows, dialog.category?.id)} onClose={() => setDialog(undefined)} onSave={async form => { if (dialog.category) await update({ id: dialog.category.id, body: form }).unwrap(); else { const result = await create(form).unwrap(); if (!dirty) setSelectedId(result.data.id); } }}/ >}
    {deleting && <DeleteDialog name={deleting.name} explanation="Move its children and remove product references first." onClose={() => setDeleting(undefined)} onDelete={async () => { await remove(deleting.id).unwrap(); setDirty(false); }}/ >}
  </div>;
}
