const { test } = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const ts = require('typescript'); const path = require('node:path');
function load(file, imports = {}) { const m = { exports: {} }; new Function('module','exports','require',ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m,m.exports,name=>imports[name]); return m.exports; }
const { withReauth } = load('redux/reauth.ts');
const deferred = () => { let resolve; const promise = new Promise(r=>resolve=r); return {promise,resolve}; };
const unauthorized = {error:{status:401,data:{message:'Expired'}}}; const success = {data:{ok:true}};
const context = () => { const actions=[]; return {api:{dispatch:a=>actions.push(a),signal:new AbortController().signal},actions}; };
test('missing access token refreshes cookie then retries the original request',async()=>{const calls=[]; const query=withReauth(async arg=>{calls.push(arg); return calls.length===1?unauthorized:success});const {api}=context();assert.deepEqual(await query('/auth/me',api,{}),success);assert.deepEqual(calls,['/auth/me',{url:'/auth/refresh',method:'POST'},'/auth/me']);});
test('concurrent and late 401s share a single successful rotation',async()=>{const gate=deferred(),late=deferred();let refreshes=0,first=0,second=0;const query=withReauth(async arg=>{if(arg.url==='/auth/refresh'){refreshes++;await gate.promise;return success}if(arg==='/one')return ++first===1?unauthorized:success;if(arg==='/two'&&++second===1){await late.promise;return unauthorized}return success});const {api}=context();const one=query('/one',api,{}),two=query('/two',api,{});await new Promise(setImmediate);gate.resolve();await one;late.resolve();await two;assert.equal(refreshes,1);assert.equal(second,2);});
test('new requests wait until rotation finishes',async()=>{const gate=deferred();let count=0,otherCalls=0;const query=withReauth(async arg=>{if(arg.url==='/auth/refresh'){await gate.promise;return success}if(arg==='/other'){otherCalls++;return success}return ++count===1?unauthorized:success});const {api}=context();const first=query('/auth/me',api,{});await new Promise(setImmediate);const other=query('/other',api,{});assert.equal(otherCalls,0);gate.resolve();await Promise.all([first,other]);assert.equal(otherCalls,1);});
test('expired refresh session clears auth and stops retrying',async()=>{const {api,actions}=context();let calls=0;const query=withReauth(async()=>{calls++;return unauthorized});assert.equal((await query('/auth/me',api,{})).error.status,401);assert.equal(calls,2);assert.deepEqual(actions,[{type:'auth/clearSession'}]);});
test('network/5xx refresh failures remain retryable rather than logging out',async()=>{for(const status of ['FETCH_ERROR',503]){const {api,actions}=context();const query=withReauth(async arg=>arg.url==='/auth/refresh'?{error:{status,data:'offline'}}:unauthorized);assert.equal((await query('/auth/me',api,{})).error.status,status);assert.equal(actions.length,0);}});
test('login and refresh failures never recursively refresh or replay credentials',async()=>{for(const url of ['/auth/login','/auth/refresh','/auth/register']){let calls=0;const query=withReauth(async()=>{calls++;return unauthorized});await query({url,method:'POST'},context().api,{});assert.equal(calls,1);}});
test('401 after a successful refresh is terminal, not an infinite retry',async()=>{const {api,actions}=context();let calls=0;const query=withReauth(async arg=>{calls++;return arg.url==='/auth/refresh'?success:unauthorized});await query('/auth/me',api,{});assert.equal(calls,3);assert.equal(actions.length,1);});
test('proxy does not redirect an expired/missing access cookie before client session recovery',()=>{const {proxy}=load('proxy.ts',{'next/server':{NextResponse:{next:()=> 'continue'}}});assert.equal(proxy({cookies:{get:()=>undefined}}),'continue');});
test('session destination preserves safe paths and rejects external/customer admin redirects',()=>{const {sessionDestination}=load('modules/auth/redirect.ts');assert.equal(sessionDestination('ADMIN','?redirect=%2Fadmin%2Fproducts%3Fpage%3D2'),'/admin/products?page=2');assert.equal(sessionDestination('ADMIN','?redirect=//evil.test'),'/admin');assert.equal(sessionDestination('CUSTOMER','?redirect=/admin/products'),'/account');});
