const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const path = require('node:path'); const ts = require('typescript');
function load(name) { const module = { exports: {} }; const file = path.join(__dirname, '../modules/product', name); const compiled = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText; new Function('module', 'exports', 'require', compiled)(module, module.exports, request => load(request.replace('./', '') + '.ts')); return module.exports; }
const { generateVariants, duplicateSelection } = load('variant-generation.ts'); const { blankVariant } = load('editor.types.ts');
const attrs = [{ id: 1, name: 'Color', isRequired: true, values: [{ id: 11, value: 'Red' }, { id: 12, value: 'Blue' }] }, { id: 2, name: 'Size', isRequired: true, values: [{ id: 21, value: 'M' }, { id: 22, value: 'L' }] }];
test('generates the Cartesian product, replacing unused placeholders', () => { const result = generateVariants(attrs, [blankVariant('initial')], 'TEE'); assert.equal(result.length, 4); assert.equal(new Set(result.map(r => r.sku)).size, 4); assert.equal(result.filter(r => r.selections[2] === 21).length, 2); });
test('repeated generation preserves existing variants and does not duplicate', () => { const first = generateVariants(attrs, [], 'TEE'); first[0].id = 7; first[0].price = '20'; first[0].stock = '12'; const second = generateVariants(attrs, first, 'TEE'); assert.equal(second.length, 4); assert.equal(second[0], first[0]); assert.equal(second[0].stock, '12'); });
test('rejects exact duplicate combinations while allowing a size in another color', () => { const row = { ...blankVariant('saved'), selections: { 1: 11, 2: 21 } }; assert.equal(duplicateSelection([row], 'new', { 2: 21, 1: 11 }), true); assert.equal(duplicateSelection([row], 'new', { 1: 12, 2: 21 }), false); assert.equal(duplicateSelection([row], 'saved', row.selections), false); });
test('new variants never inherit opening stock from existing variants', () => { const row = { ...blankVariant('saved'), id: 1, sku: 'EXISTING', selections: { 1: 11, 2: 21 }, stock: '90', price: '20' }; const result = generateVariants(attrs, [row], 'TEE'); assert.ok(result.slice(1).every(r => r.stock === '0' && r.price === '20')); });
test('rejects incomplete catalog setup and excessive combinations before allocating', () => { assert.throws(() => generateVariants([], [], 'TEE'), /Assign attributes/); assert.throws(() => generateVariants([{ ...attrs[0], values: [] }], [], 'TEE'), /active value/); const many = { ...attrs[0], values: Array.from({ length: 201 }, (_, id) => ({ id, value: String(id) })) }; assert.throws(() => generateVariants([many], [], 'TEE'), /at most 200/); });
