"use client";
import Link from "next/link";
import { useState } from "react";
import { Plus, Pencil, Trash2, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useListProductsQuery, useDeleteProductMutation, useUpdateProductStatusMutation } from "@/modules/product/productApi";
import { useEditorOptionsQuery } from "@/modules/product/editorApi";
import type { Product, ProductStatus } from "@/modules/product/types";
import { ActionNotice, DeleteDialog, EmptyPanel, ErrorPanel, LoadingPanel, selectStyle, useCatalogAction } from "@/modules/catalog/components/CatalogShared";

export default function ProductsPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState<ProductStatus | "">(""); const [category, setCategory] = useState(""); const [brand, setBrand] = useState("");
  const query = useListProductsQuery({ page, limit: 20, search: search.trim() || undefined, status: status || undefined, categoryId: category ? Number(category) : undefined, brandId: brand ? Number(brand) : undefined });
  const options = useEditorOptionsQuery(); const [remove] = useDeleteProductMutation(); const [updateStatus] = useUpdateProductStatusMutation(); const [deleting, setDeleting] = useState<Product>(); const action = useCatalogAction();
  return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Catalog</p><h1 className="text-3xl font-semibold">Products</h1><p className="mt-2 text-sm text-muted-foreground">Manage products, variants and visibility. Open the editor to review and publish.</p></div><Button nativeButton={false} render={<Link href="/admin/products/new"/>}><Plus/>Add product</Button></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Input maxLength={100} aria-label="Search products" placeholder="Search name or slug…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}/><select aria-label="Product status" className={selectStyle} value={status} onChange={e => { setStatus(e.target.value as typeof status); setPage(1); }}><option value="">All statuses</option>{["DRAFT", "ACTIVE", "INACTIVE", "ARCHIVED"].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filter category" className={selectStyle} value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="">All categories</option>{options.data?.categories.map(row => <option key={row.id} value={row.id}>{row.path ?? row.name}</option>)}</select><select aria-label="Filter brand" className={selectStyle} value={brand} onChange={e => { setBrand(e.target.value); setPage(1); }}><option value="">All brands</option>{options.data?.brands.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div>
    {options.isError && <ErrorPanel error={options.error} retry={options.refetch}/>}<ActionNotice action={action}/>
    {query.isLoading ? <LoadingPanel/> : query.isError ? <ErrorPanel error={query.error} retry={query.refetch}/> : !query.data?.data.length ? <EmptyPanel title="No products found" description="Add your first product or change the search and filters."/> : <div className="overflow-x-auto rounded-xl border bg-card" aria-busy={query.isFetching}><table className="w-full text-left text-sm"><thead className="border-b bg-muted/30 text-xs text-muted-foreground"><tr>{["Product", "Category", "Brand", "Status", "Actions"].map(label => <th key={label} className="p-4 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y">{query.data.data.map(product => <tr key={product.id}><td className="p-4"><Link href={`/admin/products/${product.id}/edit`} className="font-semibold hover:underline">{product.name}</Link><p className="mt-1 text-xs text-muted-foreground">{product.slug}</p></td><td className="p-4">{product.categories?.find(item => item.isPrimary)?.category?.name ?? "Unassigned"}</td><td className="p-4">{product.brand?.name ?? "—"}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs ${product.status === "ACTIVE" ? "bg-emerald-500/10 text-emerald-700" : "bg-muted"}`}>{product.status}</span></td><td className="p-4"><div className="flex items-center gap-2"><Button size="sm" variant="outline" nativeButton={false} render={<Link href={`/admin/products/${product.id}/edit`}/>}><Pencil/>Edit</Button>{product.status === "ACTIVE" ? <><Button size="sm" variant="ghost" disabled={action.busy} onClick={() => void action.run(() => updateStatus({ id: product.id, status: "INACTIVE" }).unwrap(), `${product.name} is now hidden.`)}>Hide</Button><Button size="icon-sm" variant="ghost" aria-label={`View ${product.name}`} nativeButton={false} render={<Link href={`/products/${product.slug}`} target="_blank" rel="noopener noreferrer"/>}><ExternalLink/></Button></> : <Button size="sm" variant="ghost" nativeButton={false} render={<Link href={`/admin/products/${product.id}/edit`}/>}>Review & publish</Button>}<Button size="icon-sm" variant="ghost" disabled={action.busy} aria-label={`Delete ${product.name}`} onClick={() => setDeleting(product)}><Trash2/></Button></div></td></tr>)}</tbody></table></div>}
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">{query.data?.meta.total ?? 0} products · Page {page} of {Math.max(1, query.data?.meta.totalPages ?? 1)}</p><div className="flex gap-2"><Button variant="outline" disabled={page === 1 || query.isFetching} onClick={() => setPage(page - 1)}>Previous</Button><Button variant="outline" disabled={page >= (query.data?.meta.totalPages ?? 1) || query.isFetching} onClick={() => setPage(page + 1)}>Next</Button></div></div>
    {deleting && <DeleteDialog name={deleting.name} explanation="This removes the product and its associated catalog data. Existing order references may prevent deletion." onClose={() => setDeleting(undefined)} onDelete={async () => { await remove(deleting.id).unwrap(); if (query.data?.data.length === 1 && page > 1) setPage(page - 1); }}/ >}
  </div>;
}
